workflows:
  android-workflow:
    name: RegiBot Build
    max_build_duration: 15
    instance_type: mac_mini_m2
    environment:
      groups:
        - android
      vars:
        PACKAGE_NAME: "com.juancavr6.regibot"
      node: latest
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          if [ -d "app" ]; then
            echo "sdk.dir=$ANDROID_SDK_ROOT" > app/local.properties
          fi
      - name: Build Android APK
        script: |
          if [ -f ./gradlew ]; then
            chmod +x gradlew
            ./gradlew assembleDebug
          elif [ -f ./app/gradlew ]; then
            cd app
            chmod +x gradlew
            ./gradlew assembleDebug
          elif [ -f ./app/build.gradle ]; then
            cd app
            gradle assembleDebug
          else
            gradle assembleDebug
          fi
    artifacts:
      - "app/build/outputs/apk/**/*.apk"
      - "**/build/outputs/apk/**/*.apk"
